In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [2]:
# Create a 1-dimensional NumPy array using np.array()
# Create a 2-dimensional NumPy array using np.array()
# Create a 3-dimensional Numpy array using np.array()
a1 = np.array(
    [1,2,3])
a2 = np.array([[1,2,3], 
               [4,5,6]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])


In [3]:
# Attributes of 1-dimensional array (shape,
# number of dimensions, data type, size and type)
a1.shape , a1.ndim , a1.dtype, a1.size

((3,), 1, dtype('int32'), 3)

In [4]:
# Attributes of 2-dimensional array
a2.shape , a2.ndim , a2.dtype, a2.size

((2, 3), 2, dtype('int32'), 6)

In [5]:
# Attributes of 3-dimensional array
a3.shape , a3.ndim , a3.dtype, a3.size

((2, 3, 3), 3, dtype('int32'), 18)

In [103]:
# Import pandas and create a DataFrame out of one of the arrays you've created
import pandas as pd
df = pd.DataFrame(a2, columns=['A', 'B', 'C'])

In [7]:
# Create an array of shape (10, 2) with only ones
ones = np.ones([10,2]) 
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros([7,2,3])
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
step = np.arange(0,100,3)
step

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.randint(0,10,(7,2))

array([[7, 9],
       [4, 5],
       [7, 7],
       [1, 4],
       [3, 1],
       [1, 5],
       [7, 0]])

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
rfloat = np.random.rand(3,5)
rfloat

array([[0.00441128, 0.75078774, 0.59630709, 0.67787478, 0.97765516],
       [0.44204092, 0.22132823, 0.33525465, 0.44977552, 0.37509307],
       [0.58986764, 0.59916197, 0.90866323, 0.22009447, 0.52901076]])

In [12]:
# Set the random seed to 42
# Create a random array of numbers between 0 & 10 of size (4, 6)
np.random.seed(42)
np.random.randint(0,10,(4,6))

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [13]:
#Create an array of random numbers between 1 & 10 of size (3, 7) and save it to a variable
# Find the unique numbers in the array you just created
a4= np.random.randint(1,10,(3,7))
a4

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2],
       [4, 9, 2, 9, 5, 2, 4]])

In [15]:
# Find the 0'th index of the latest array you created
a4[0][0]

9

In [14]:
# Get the first 2 rows of latest array you created
a4[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [16]:
# Get the first 2 values of the first 2 rows of the latest array
a4[:2, :2]

array([[9, 1],
       [5, 3]])

In [33]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
a5 = np.random.randint(0,10,(3,5))
ones = np.ones((3,5))

In [60]:
# Add the two arrays together
sum= a5 + ones
sum

array([[10.,  2., 10.,  4.,  8.],
       [ 7.,  9.,  8.,  5.,  2.],
       [ 5.,  8., 10.,  9.,  9.]])

In [61]:
#Create another array of ones of shape (5, 3)
ones_1 = np.ones((5,3))

In [62]:
# Try add the array of ones and the other most recent array together
sum = ones_1 + ones

ValueError: operands could not be broadcast together with shapes (5,3) (3,5) 

In [73]:
# Create another array of ones of shape (3, 5)
ones_2 = np.ones((3,5))

In [74]:
# Subtract the new array of ones from the other most recent array
sum -= ones_2

In [75]:
# Multiply the ones array with the latest array
mult= ones_2 * sum

In [76]:
# Take the latest array to the power of 2 using '**'
mult ** 2

array([[64.,  0., 64.,  4., 36.],
       [25., 49., 36.,  9.,  0.],
       [ 9., 36., 64., 49., 49.]])

In [78]:
# Do the same thing with np.square()
np.square(mult)

array([[64.,  0., 64.,  4., 36.],
       [25., 49., 36.,  9.,  0.],
       [ 9., 36., 64., 49., 49.]])

In [79]:
# Find the mean of the latest array using np.mean()
np.mean(mult)

5.066666666666666

In [80]:
# Find the maximum of the latest array using np.max()
np.max(mult)

8.0

In [81]:
# Find the minimum of the latest array using np.min()
np.min(mult)

0.0

In [82]:
# Find the standard deviation of the latest array
np.std(mult)

2.6948510575210314

In [83]:
# Find the variance of the latest array
np.var(mult)

7.262222222222222

In [84]:
# Reshape the latest array to (3, 5, 1)
np.reshape(mult, (3,5,1))

array([[[8.],
        [0.],
        [8.],
        [2.],
        [6.]],

       [[5.],
        [7.],
        [6.],
        [3.],
        [0.]],

       [[3.],
        [6.],
        [8.],
        [7.],
        [7.]]])

In [85]:
# Transpose the latest array
mult.T

array([[8., 5., 3.],
       [0., 7., 6.],
       [8., 6., 8.],
       [2., 3., 7.],
       [6., 0., 7.]])

In [86]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random1 = np.random.randint(0, 10, (3,3))
random2 = np.random.randint(0, 10, (3,2))

In [87]:
# Perform a dot product on the two newest arrays you created
np.dot(random1, random2)

array([[16, 40],
       [14, 70],
       [14, 71]])

In [88]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random3 = np.random.randint(0, 10, (4,3))
random4 = np.random.randint(0, 10, (4,3))

In [89]:
# Perform a dot product on the two newest arrays you created
np.dot(random3, random4)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

In [90]:
# Take the latest two arrays, perform a transpose on one of them and then perform
# a dot product on them both
np.dot(random3, random4.T)

array([[111,  57,  60, 105],
       [100,  52,  56,  96],
       [ 30,  37,  18,   4],
       [ 85,  42,  50,  87]])

In [91]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
arr1 = np.random.randint(0, 10, (2,2))
arr2 = np.random.randint(0, 10, (2,2))
arr1

array([[6, 6],
       [8, 9]])

In [92]:
# Compare the two arrays with '>'
arr1 > arr2

array([[False,  True],
       [ True,  True]])

In [93]:
# Compare the two arrays with '>='
arr1 >= arr2

array([[False,  True],
       [ True,  True]])

In [94]:
# Find which elements of the first array are greater than 7
mask = arr1 > 7
arr1[mask]

array([8, 9])

In [95]:
# Which parts of each array are equal? (try using '==')
mask = arr1 == arr2
arr1[mask]

array([], dtype=int32)

In [96]:
# Sort one of the arrays you just created in ascending order
np.sort(arr1)

array([[6, 6],
       [8, 9]])

In [97]:
# Sort the indexes of one of the arrays you just created
np.argsort(arr1, axis=1)

array([[0, 1],
       [0, 1]], dtype=int64)

In [98]:
# Find the index with the maximum value in one of the arrays you've created
np.unravel_index(np.argmax(arr1), arr1.shape)

(1, 1)

In [99]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(arr1, axis=1)


array([0, 1], dtype=int64)

In [100]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(arr1, axis=0)

array([0, 0], dtype=int64)

In [101]:
# Create an array of normally distributed random numbers
normally_distribute = np.random.randn(3,4)
normally_distribute

array([[ 0.09176078, -1.98756891, -0.21967189,  0.35711257],
       [ 1.47789404, -0.51827022, -0.8084936 , -0.50175704],
       [ 0.91540212,  0.32875111, -0.5297602 ,  0.51326743]])

In [102]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])